---
- name: Unpack node archive
  unarchive: src="http://nodejs.org/dist/v{{ nodejs_version }}/node-v{{ nodejs_version }}-linux-x64.tar.gz" dest="/usr/local" copy=no
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C

- name: Create node directory symlink
  file: src=/usr/local/node-v{{ nodejs_version }}-linux-x64 dest=/usr/local/node state=link

- name: Create node binary symlink
  file: src=/usr/local/node/bin/node dest=/usr/local/bin/node state=link

- name: Create npm binary symlink
  file: src=/usr/local/node/bin/npm dest=/usr/local/bin/npm state=link

...
