---

- apt: name=apt-transport-https state=present

- name: Add sury public key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- apt_repository:
    repo: deb https://packages.sury.org/php/ jessie main
    state: present
    filename: sury

- name: Installation de PHP 5
  apt:
    name: php5
    state: present

- name: Installation des extensions
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5-curl
    - php5-mysqlnd

- name: Activation des extensions
  shell: "php5enmod {{ item }}"
  with_items:
    - curl
    - mysqli

- name: Installation de PHP 7
  apt:
    name: php7.0 ## Version en prod actuellement
    state: present

- name: Installation des extensions PHP 7
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0-curl
    - php7.0-mysqlnd
    - php7.0-xml

- name: Activation des extensions PHP 7
  shell: "phpenmod -v 7.0 {{ item }}"
  with_items:
    - curl
    - mysqli
    - xml
...