- 
  hosts: 127.0.0.1
  gather_facts: no
  vars:
    deploy_repository: "http://github.com/afup/web.git"
    deploy_path: "/home/sources/web"
    deploy_branch: "master"
    custom_shared_dir: "/home/afup/afup.org/shared"
    event_custom_shared_dir: "/home/afup/event.afup.org/web"
    cache_dir: "cache"
  tasks:
    - deploy_helper:
        path: "{{ deploy_path }}"
    - git:
        repo: "{{ deploy_repository }}"
        dest: "{{ custom_shared_dir }}/{{ cache_dir }}"
        accept_hostkey: True
        version: "{{ deploy_branch }}"
        depth: 1
        force: yes
      register: git_clone_result
    - get_url:
        url: https://getcomposer.org/installer
        dest: "{{ custom_shared_dir }}/{{ cache_dir }}/composer_installer"
    - shell: "cat {{ custom_shared_dir }}/{{ cache_dir }}/composer_installer | php -- --install-dir={{ custom_shared_dir }}/{{ cache_dir }}"
      environment:
        COMPOSER_HOME: "/tmp/tmp_composer_home_deploy"
    - shell: "php composer.phar install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction --working-dir={{ item }}"
      environment:
        COMPOSER_HOME: "/tmp/tmp_composer_home_deploy"
      args:
        chdir: "{{ custom_shared_dir }}/{{ cache_dir }}"
      with_items:
        - "{{ custom_shared_dir }}/{{ cache_dir }}/event"
        - "{{ custom_shared_dir }}/{{ cache_dir }}"
    - file:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/composer_installer"
        state: absent
    - file:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/composer.phar"
        state: absent

    - apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present
        filename: yarn

    - apt:
        name: yarn
        state: present

    - stat:
        file: "{{ deploy_helper.new_release_path }}/package.json"
        register: packages

    - shell: "yarn install --prod --non-interactive"
      args:
        chdir: "{{ deploy_helper.new_release_path }}"
      when: packages.stat.exists

    - synchronize:
        src: "{{ custom_shared_dir }}/{{ cache_dir }}"
        dest: "{{ deploy_helper.new_release_path }}"
        rsync_opts:
          - "--exclude=.git"
    
    - file:
        path: "{{deploy_helper.new_release_path }}/{{ item }}"
        state: absent
      with_items:
        - "app/config/parameters.yml.dist-docker"
        - "htdocs/templates/forumphp2016/images/intervenants"
        - "htdocs/templates/forumphp2005/talks"
        - "var/logs"
        - "event/wp/wp-content/plugins/hello.php"
        - "event/wp/composer.json"

    - file:
        path: "{{ deploy_helper.new_release_path }}/{{ item }}"
        src: "{{ custom_shared_dir }}/{{ item }}"
        state: link
      with_items:
        - "htdocs/templates/forumphp2016/images/intervenants"
        - "htdocs/templates/forumphp2005/talks"
        - "htdocs/templates/forumphp2006/talks"
        - "htdocs/templates/forumphp2007/talks"
        - "htdocs/templates/forumphp2008/images/intervenants"
        - "htdocs/templates/forumphp2009/images/intervenants"
        - "htdocs/templates/forumphp2010/images/intervenants"
        - "htdocs/templates/forumphp2012/images/intervenants"
        - "htdocs/templates/forumphp2013/images/intervenants"
        - "htdocs/templates/forumphp2014/images/intervenants"
        - "htdocs/templates/forumphp2015/images/intervenants"
        - "tmp"
        - "cron/mailchimp.log"
        - "cron/notifications_stats_ticket.log"
        - "cron/reminder.log"
        - "cron/twitterbot.log"
        - "cron/explorePlanete.log"
        - "cron/syncAfupRedmine.log"
        - "cron/syncAfupSympa.log"
        - "app/config/parameters.yml"
        - "htdocs/templates/forumphp2008/resumes"
        - "htdocs/templates/forumphp2009/resumes"
        - "htdocs/templates/forumphp2012/resumes"
        - "htdocs/templates/forumphp2013/resumes"
        - "htdocs/templates/phptourclermont2016/images/intervenants"
        - "htdocs/templates/phptourlille2011/images/intervenants"
        - "htdocs/templates/phptourluxembourg2015/images/intervenants" 
        - "htdocs/templates/phptourlyon2014/images/intervenants"
        - "htdocs/templates/phptournantes2012/images/intervenants"
        - "htdocs/templates/site/images"
        - "htdocs/wiki/files"
        - "htdocs/wiki/wakka.config.php"
        - "htdocs/uploads"
        - "configs/application/config.php"
        - "htdocs/docs"
        - "var/logs"

    - file:
        path: "{{ deploy_helper.new_release_path }}/event/wp/{{ item.target }}"
        src: "{{ event_custom_shared_dir }}/{{ item.src }}"
        state: link
      with_items:
        - src   : "wp-content/uploads"
          target: "wp-content/uploads"
        - src   : "wp-config.php"
          target: "wp-config.php"


    - deploy_helper:
        path: "{{ deploy_path }}"
        release: '{{ deploy_helper.new_release }}'
        state: finalize
        keep_releases: 4

    - shell: sudo /usr/sbin/apache2ctl graceful
      args:
        warn: False

