- 
  hosts: 127.0.0.1
  gather_facts: no
  vars:
    deploy_repository: "http://github.com/afup/web.git"
    deploy_path: "/home/sources/web"
    deploy_branch: "master"
    custom_shared_dir: "/home/afup/afup.org/shared"
    event_custom_shared_dir: "/home/afup/event.afup.org/web"
    cache_dir: "cache"
  tasks:
    - include_vars: ../vars/static.yml
    - name: "Preparing deploy folder"
      deploy_helper:
        path: "{{ deploy_path }}"

    - name: "Getting sources from git"
      git:
        repo: "{{ deploy_repository }}"
        dest: "{{ custom_shared_dir }}/{{ cache_dir }}"
        accept_hostkey: True
        version: "{{ deploy_branch }}"
        depth: 1
        force: yes
      register: git_clone_result
      no_log: True

    - name: "Removing static files and directories from git repository"
      file:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/{{ item }}"
        state: absent
        force: yes
      with_items:
        - "{{ static_files }}"
        - "{{ static_directories }}"
   
    - name: "Linking config files"
      file:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/{{ item }}"
        src: "{{ custom_shared_dir }}/{{ item }}"
        state: link
        force: yes
      with_items:
        - "{{ static_files }}"
        - "{{ static_directories }}"

    - name: "Downloading composer"
      get_url:
        url: https://getcomposer.org/installer
        dest: "{{ custom_shared_dir }}/{{ cache_dir }}/composer_installer"

    - name: "Installing composer"
      shell: "cat {{ custom_shared_dir }}/{{ cache_dir }}/composer_installer | php -- --install-dir={{ custom_shared_dir }}/{{ cache_dir }}"
      environment:
        COMPOSER_HOME: "/tmp/tmp_composer_home_deploy"

    - name: "Installing composer dependencies"
      shell: "php composer.phar install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction --working-dir={{ item }}"
      environment:
        COMPOSER_HOME: "/tmp/tmp_composer_home_deploy"
        SYMFONY_ENV: prod
      args:
        chdir: "{{ custom_shared_dir }}/{{ cache_dir }}"
      with_items:
        - "{{ custom_shared_dir }}/{{ cache_dir }}/event"
        - "{{ custom_shared_dir }}/{{ cache_dir }}"

    - name: "Removing composer installer"
      file:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/composer_installer"
        state: absent

    - name: "Removing composer.phar"
      file:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/composer.phar"
        state: absent

    - name: "Checking for package.json"
      stat:
        path: "{{ custom_shared_dir }}/{{ cache_dir }}/package.json"
      register: packages

    - name: "Installing yarn dependancies"
      shell: "yarn install --prod --non-interactive"
      args:
        chdir: "{{ custom_shared_dir }}/{{ cache_dir }}"
      when: packages.stat.exists

    - name: "Synchronizing files to the deploy folder"
      synchronize:
        src: "{{ custom_shared_dir }}/{{ cache_dir }}/"
        dest: "{{ deploy_helper.new_release_path }}"
        rsync_opts:
          - "--exclude=.git"

    - name: "Running npm build (webpack)"
      shell: "/usr/local/bin/npm run build"
      args:
        chdir: "{{ deploy_helper.new_release_path }}"
      when: packages.stat.exists

    - name: "Creating event.afup.org symlinks"
      file:
        path: "{{ deploy_helper.new_release_path }}/event/wp/{{ item.target }}"
        src: "{{ event_custom_shared_dir }}/{{ item.src }}"
        state: link
      with_items:
        - src   : "wp-content/uploads"
          target: "wp-content/uploads"
        - src   : "wp-config.php"
          target: "wp-config.php"

    - name: "Removing unnecessary files/folders"
      file:
        path: "{{deploy_helper.new_release_path }}/{{ item }}"
        state: absent
      with_items:
        - "app/config/parameters.yml.dist-docker"
        - "htdocs/templates/forumphp2016/images/intervenants"
        - "htdocs/templates/forumphp2005/talks"
        - "var/logs"
        - "event/wp/wp-content/plugins/hello.php"
        - "event/wp/composer.json"

    - name: "Changing current symlink"
      deploy_helper:
        path: "{{ deploy_path }}"
        release: '{{ deploy_helper.new_release }}'
        state: finalize
        keep_releases: 4

    - name: "Reloading apache"
      shell: sudo /usr/sbin/apache2ctl graceful
      args:
        warn: False

